/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;
import projetoparalelepipedo.ClasseCone;

/**
 *
 * @author Alex
 */
public class TelaInternaCone extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaInternaCone
     */
    public TelaInternaCone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextFieldRaioCone = new javax.swing.JTextField();
        TextFieldAlturaCone = new javax.swing.JTextField();
        LabelResultadoCone = new javax.swing.JLabel();
        LabelResultadoCone2 = new javax.swing.JLabel();
        LabelResultadoCone3 = new javax.swing.JLabel();
        BotaoExecutarCone = new javax.swing.JButton();
        LabelResultadoCone4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cone");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Raio");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Altura");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TextFieldRaioCone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldRaioCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldRaioConeActionPerformed(evt);
            }
        });

        TextFieldAlturaCone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LabelResultadoCone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelResultadoCone.setText("Resultado");
        LabelResultadoCone.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        LabelResultadoCone2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelResultadoCone2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        LabelResultadoCone3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelResultadoCone3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        BotaoExecutarCone.setText("Executar");
        BotaoExecutarCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExecutarConeActionPerformed(evt);
            }
        });

        LabelResultadoCone4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelResultadoCone4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextFieldRaioCone, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(TextFieldAlturaCone))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(LabelResultadoCone, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(BotaoExecutarCone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelResultadoCone3)
                            .addComponent(LabelResultadoCone2)
                            .addComponent(LabelResultadoCone4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(TextFieldRaioCone, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(TextFieldAlturaCone, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(BotaoExecutarCone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LabelResultadoCone, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelResultadoCone2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelResultadoCone3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelResultadoCone4)
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldRaioConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldRaioConeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldRaioConeActionPerformed

    private void BotaoExecutarConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExecutarConeActionPerformed
    // TODO add your handling code here:
        try {
             ClasseCone cone = new ClasseCone();

            cone.setRaio(Float.parseFloat(TextFieldRaioCone.getText()));
            cone.setAltura(Float.parseFloat(TextFieldAlturaCone.getText()));

            LabelResultadoCone.setText("A geratriz do cone é;" + cone.calcularGeratriz());
            LabelResultadoCone2.setText("A área total do cone é;" + cone.calcularAreaTotalCone());
            LabelResultadoCone3.setText("A área lateral do cone é;" + cone.calcularLaterallCone());
            LabelResultadoCone4.setText("O volume do cone é;" + cone.calcularVolume());
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_BotaoExecutarConeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoExecutarCone;
    private javax.swing.JLabel LabelResultadoCone;
    private javax.swing.JLabel LabelResultadoCone2;
    private javax.swing.JLabel LabelResultadoCone3;
    private javax.swing.JLabel LabelResultadoCone4;
    private javax.swing.JTextField TextFieldAlturaCone;
    private javax.swing.JTextField TextFieldRaioCone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
