/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import projetoparalelepipedo.ClasseCilindro;

/**
 *
 * @author Alex
 */
public class TelaInternaCilindro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaInternaCilindro
     */
    public TelaInternaCilindro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextFieldCilindroAltura = new javax.swing.JTextField();
        TextFieldCilindroRaio = new javax.swing.JTextField();
        LabelResultadoCilindro = new javax.swing.JLabel();
        BotaoExecutarParalelepipedo = new javax.swing.JButton();
        LabelResultadoCilindro2 = new javax.swing.JLabel();
        LabelResultadoCilindro3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cilindro");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Raio");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Altura");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TextFieldCilindroAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldCilindroAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCilindroAlturaActionPerformed(evt);
            }
        });

        TextFieldCilindroRaio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldCilindroRaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCilindroRaioActionPerformed(evt);
            }
        });

        LabelResultadoCilindro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelResultadoCilindro.setText("Resultado");
        LabelResultadoCilindro.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        BotaoExecutarParalelepipedo.setText("Executar");
        BotaoExecutarParalelepipedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExecutarParalelepipedoActionPerformed(evt);
            }
        });

        LabelResultadoCilindro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelResultadoCilindro2.setToolTipText("");

        LabelResultadoCilindro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelResultadoCilindro3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelResultadoCilindro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldCilindroRaio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(TextFieldCilindroAltura))
                .addGap(36, 36, 36)
                .addComponent(BotaoExecutarParalelepipedo)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelResultadoCilindro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelResultadoCilindro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 27, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldCilindroRaio, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldCilindroAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelResultadoCilindro, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(BotaoExecutarParalelepipedo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelResultadoCilindro3, javax.swing.GroupLayout.DEFAULT_SIZE, 9, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelResultadoCilindro2, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldCilindroRaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCilindroRaioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCilindroRaioActionPerformed

    private void TextFieldCilindroAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCilindroAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCilindroAlturaActionPerformed

    private void BotaoExecutarParalelepipedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExecutarParalelepipedoActionPerformed
        // TODO add your handling code here:
        ClasseCilindro cilindro = new ClasseCilindro();
        
        cilindro.setRaio(Float.parseFloat(TextFieldCilindroRaio.getText()));
        cilindro.setAltura(Float.parseFloat(TextFieldCilindroAltura.getText()));
        
        LabelResultadoCilindro.setText("A área do cilindro é: " + cilindro.calcularAreaTotalCilindro());
        LabelResultadoCilindro2.setText("A lateral do cilindro é: " + cilindro.calcularLateralCilindro());
        LabelResultadoCilindro3.setText("O volume do cilindro é: " + cilindro.calcularVolumeCilindro());
    }//GEN-LAST:event_BotaoExecutarParalelepipedoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoExecutarParalelepipedo;
    private javax.swing.JLabel LabelResultadoCilindro;
    private javax.swing.JLabel LabelResultadoCilindro2;
    private javax.swing.JLabel LabelResultadoCilindro3;
    private javax.swing.JTextField TextFieldCilindroAltura;
    private javax.swing.JTextField TextFieldCilindroRaio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
