/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import projetoparalelepipedo.ClasseParalelepipedo;

/**
 *
 * @author Alex
 */
public class TelaInternaParalelepipedo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaParalelepipedo
     */
    public TelaInternaParalelepipedo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldParalelepipedoAltura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextFieldParalelepipedoLargura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextFieldParalelepipedoComprimento = new javax.swing.JTextField();
        LabelResultadoParalelepipedo = new javax.swing.JLabel();
        BotaoExecutarParalelepipedo = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Paralelepípedo");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Altura");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setAutoscrolls(true);

        TextFieldParalelepipedoAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldParalelepipedoAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldParalelepipedoAlturaActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Largura");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TextFieldParalelepipedoLargura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldParalelepipedoLargura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldParalelepipedoLarguraActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Comprimento");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TextFieldParalelepipedoComprimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LabelResultadoParalelepipedo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelResultadoParalelepipedo.setText("Resultado");
        LabelResultadoParalelepipedo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        BotaoExecutarParalelepipedo.setText("Executar;");
        BotaoExecutarParalelepipedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExecutarParalelepipedoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldParalelepipedoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextFieldParalelepipedoLargura)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(TextFieldParalelepipedoComprimento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(LabelResultadoParalelepipedo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(BotaoExecutarParalelepipedo)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldParalelepipedoAltura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldParalelepipedoLargura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextFieldParalelepipedoComprimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoExecutarParalelepipedo)
                    .addComponent(LabelResultadoParalelepipedo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldParalelepipedoLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldParalelepipedoLarguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldParalelepipedoLarguraActionPerformed

    private void TextFieldParalelepipedoAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldParalelepipedoAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldParalelepipedoAlturaActionPerformed

    private void BotaoExecutarParalelepipedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExecutarParalelepipedoActionPerformed
        // TODO add your handling code here:
        ClasseParalelepipedo paralelepipedo = new ClasseParalelepipedo();
        
        paralelepipedo.setAltura(Float.parseFloat(TextFieldParalelepipedoAltura.getText()));
        paralelepipedo.setComprimento(Float.parseFloat(TextFieldParalelepipedoComprimento.getText()));
        paralelepipedo.setLargura(Float.parseFloat(TextFieldParalelepipedoLargura.getText()));
        
        String saida = "";
        saida += "Volume; " + paralelepipedo.calcularVolumeParalelepipedo() + " ";
        saida += "Área; " + paralelepipedo.calcularAreaParalelepipedo() + "\n";
        
        LabelResultadoParalelepipedo.setText(saida);
    }//GEN-LAST:event_BotaoExecutarParalelepipedoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoExecutarParalelepipedo;
    private javax.swing.JLabel LabelResultadoParalelepipedo;
    private javax.swing.JTextField TextFieldParalelepipedoAltura;
    private javax.swing.JTextField TextFieldParalelepipedoComprimento;
    private javax.swing.JTextField TextFieldParalelepipedoLargura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
