/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package package_piramide_view;

import package_piramide_model.Class_Piramide;

/**
 *
 * @author Alex
 */
public class JInternalFrame_Piramide extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrame_Piramide
     */
    public JInternalFrame_Piramide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Base = new javax.swing.JTextField();
        jTextField_Altura = new javax.swing.JTextField();
        jButton_VolumePiramide = new javax.swing.JButton();
        jLabel_ResultadoP = new javax.swing.JLabel();

        setClosable(true);

        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Volume da Pirâmide");
        jLabel_Titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel_Titulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Base");

        jLabel2.setText("Altura");

        jTextField_Base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_BaseActionPerformed(evt);
            }
        });

        jButton_VolumePiramide.setText("Calcular");
        jButton_VolumePiramide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolumePiramideActionPerformed(evt);
            }
        });

        jLabel_ResultadoP.setText("                             ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel_Titulo)
                                .addGap(137, 137, 137))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_ResultadoP)
                                    .addComponent(jButton_VolumePiramide))
                                .addGap(156, 156, 156))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_Base, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 51, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_VolumePiramide)
                .addGap(18, 18, 18)
                .addComponent(jLabel_ResultadoP)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_BaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_BaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_BaseActionPerformed

    private void jButton_VolumePiramideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolumePiramideActionPerformed
        // TODO add your handling code here:
        float base = Float.parseFloat(jTextField_Base.getText());
        float altura = Float.parseFloat(jTextField_Altura.getText());
        
        Class_Piramide objeto = new Class_Piramide(base, altura);
        
        jLabel_ResultadoP.setText("O volume dessa pirâmide é de: " + objeto.calcularVolume(base, altura));
    }//GEN-LAST:event_jButton_VolumePiramideActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_VolumePiramide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_ResultadoP;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JTextField jTextField_Altura;
    private javax.swing.JTextField jTextField_Base;
    // End of variables declaration//GEN-END:variables
}
