/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import classe.ClasseEleitor;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class TelaInternaTipoDeEleitor extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaTipoDeEleitor
     */
    public TelaInternaTipoDeEleitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoCalcularTipoDeEleitor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldNomeCompletoEleitor = new java.awt.TextField();
        textFieldAnoDeNascimentoEleitor = new java.awt.TextField();
        labelResposta = new java.awt.Label();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tipo De Eleitor");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoCalcularTipoDeEleitor.setText("Verificar");
        botaoCalcularTipoDeEleitor.setAlignmentY(0.0F);
        botaoCalcularTipoDeEleitor.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        botaoCalcularTipoDeEleitor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoCalcularTipoDeEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularTipoDeEleitorActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Completo");

        jLabel3.setText("Ano de Nascimento");

        textFieldNomeCompletoEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeCompletoEleitorActionPerformed(evt);
            }
        });

        textFieldAnoDeNascimentoEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAnoDeNascimentoEleitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(botaoCalcularTipoDeEleitor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldNomeCompletoEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldAnoDeNascimentoEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 184, Short.MAX_VALUE)
                .addComponent(labelResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(textFieldNomeCompletoEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(textFieldAnoDeNascimentoEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(botaoCalcularTipoDeEleitor)
                .addGap(20, 20, 20)
                .addComponent(labelResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        labelResposta.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCalcularTipoDeEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularTipoDeEleitorActionPerformed
        // TODO add your handling code here:
        try {
            ClasseEleitor p1 = new ClasseEleitor();
            String saida = "";
        
            p1.setNomeCompleto(textFieldNomeCompletoEleitor.getText());
            p1.setAnoDeNascimento(Integer.parseInt(textFieldAnoDeNascimentoEleitor.getText()));
        
            saida += "\n" + p1.getNomeCompleto() + " é um ";
            saida += "\n" + p1.tipoDeEleitor(p1.getAnoDeNascimento()) + "\n";
            
            labelResposta.setText(saida);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_botaoCalcularTipoDeEleitorActionPerformed

    private void textFieldNomeCompletoEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeCompletoEleitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeCompletoEleitorActionPerformed

    private void textFieldAnoDeNascimentoEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAnoDeNascimentoEleitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAnoDeNascimentoEleitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCalcularTipoDeEleitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Label labelResposta;
    private java.awt.TextField textFieldAnoDeNascimentoEleitor;
    private java.awt.TextField textFieldNomeCompletoEleitor;
    // End of variables declaration//GEN-END:variables
}
